name: Example Workflow
on:
  push:
    branches:
      - main
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "::error::This is an error message"
          echo "::warning::This is a warning message"
          echo "::debug::This is a debug message"
